version: "3.8"
services:
  pgsql:
    image: postgres:latest
    container_name: pgsql-dev
    restart: unless-stopped
    ports:
      - "5454:5432"
    networks:
      - postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # volumes:
    #   - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    links:
      - pgsql
    depends_on:
      - pgsql
    restart: unless-stopped
    ports:
      - "4001:80"
    networks:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${UI_USER}
      PGADMIN_DEFAULT_PASSWORD: ${UI_PASSWORD}
    # volumes:
    #   - pgadmin-data:/var/lib/pgadmin

networks:
  postgres:
    driver: bridge

# volumes:
#   local_pgdata:
#   pgadmin-data: