services:
  newman:
    image: postman/newman:alpine
    container_name: postmanTests
    command:
      run ses-sql-docker-brief.postman_collection.json 
      -e ses-sql-docker-brief.postman_environment.json
      -k
      -r cli,json      
      --reporter-json-export="results.json"
    volumes:
      - ../testing/ses-sql:/etc/newman
    networks:
      - internal
networks:
  internal:
    driver: bridge
