version: "3.8"
services:
  pgsql:
    image: postgres:latest
    container_name: pgsql-dev-ses-sql
    restart: unless-stopped
    ports:
      - "5454:5432"
    networks:
      - local
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # volumes:
    #   - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-ses-sql
    links:
      - pgsql
    depends_on:
      - pgsql
    restart: unless-stopped
    ports:
      - "4001:80"
    networks:
      - local
    environment:
      PGADMIN_DEFAULT_EMAIL: ${UI_USER}
      PGADMIN_DEFAULT_PASSWORD: ${UI_PASSWORD}
    # volumes:
    #   - pgadmin-data:/var/lib/pgadmin
  authsessql:
    image: auth-ses-sql
    container_name: auth-ses-sql-starter
    links:
      - pgsql
    depends_on:
      - pgsql
    restart: unless-stopped
    ports:
      - 3005:3005
    env_file:
      - .env_ns
    networks:
      - local
networks:
  local:
    driver: bridge

# volumes:
#   local_pgdata:
#   pgadmin-data: